// <auto-generated />
using IdSrv.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdSrv.Data.Migrations.IS4UsersMigrations
{
    [DbContext(typeof(IS4DbContext))]
    [Migration("20190411125443_ConfigsMigration")]
    partial class ConfigsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdSrv.Data.Models.IS4Tenant", b =>
                {
                    b.Property<string>("TenantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoginType");

                    b.Property<string>("Name");

                    b.Property<string>("Protocol");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("IdSrv.Data.Models.IS4User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("TenantId");

                    b.Property<string>("UserClaimsId");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserClaimsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IdSrv.Data.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("UserClaimsId");

                    b.HasKey("RoleId");

                    b.HasIndex("UserClaimsId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("IdSrv.Data.Models.UserClaims", b =>
                {
                    b.Property<string>("UserClaimsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("GivenName");

                    b.Property<string>("Name");

                    b.HasKey("UserClaimsId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("IdSrv.Data.Models.UserRole", b =>
                {
                    b.Property<string>("UserRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleId");

                    b.Property<string>("UserId");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("IdSrv.Data.Models.IS4User", b =>
                {
                    b.HasOne("IdSrv.Data.Models.IS4Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId");

                    b.HasOne("IdSrv.Data.Models.UserClaims", "UserClaims")
                        .WithMany()
                        .HasForeignKey("UserClaimsId");
                });

            modelBuilder.Entity("IdSrv.Data.Models.Role", b =>
                {
                    b.HasOne("IdSrv.Data.Models.UserClaims")
                        .WithMany("Roles")
                        .HasForeignKey("UserClaimsId");
                });

            modelBuilder.Entity("IdSrv.Data.Models.UserRole", b =>
                {
                    b.HasOne("IdSrv.Data.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("IdSrv.Data.Models.IS4User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
